# Example: Multi-Repo Release Orchestrator
# Use this in: c3-platform
# Location: .github/workflows/orchestrate-release.yml

name: Orchestrate Release

on:
  repository_dispatch:
    types: [dependency-updated]
  workflow_dispatch:
    inputs:
      package:
        description: 'Package that was updated (e.g., c3-shared)'
        required: true
        type: string
      version:
        description: 'New version'
        required: true
        type: string
      release_type:
        description: 'Release type'
        required: false
        default: 'dev'
        type: choice
        options:
          - dev
          - canary
          - patch
          - minor
          - major

jobs:
  determine-downstream:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.deps.outputs.repos }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine downstream repositories
        id: deps
        run: |
          # Define dependency graph
          declare -A deps=(
            ["c3-shared"]="c3-parsing c3-compliance c3-projection c3-discovery c3-wiring"
            ["c3-parsing"]="c3-compliance c3-projection c3-discovery c3-wiring"
            ["c3-compliance"]="c3-discovery c3-wiring"
            ["c3-projection"]="c3-wiring"
            ["c3-discovery"]="c3-wiring"
            ["c3-wiring"]="c3-bff c3-cli"
          )
          
          PACKAGE="${{ inputs.package || github.event.client_payload.package }}"
          PACKAGE_NAME=$(echo "$PACKAGE" | sed 's/.*\///')
          
          if [ -n "${deps[$PACKAGE_NAME]}" ]; then
            REPOS="${deps[$PACKAGE_NAME]}"
            echo "repos=[$(echo $REPOS | sed 's/ /","/g' | sed 's/^/"/' | sed 's/$/"/')]" >> $GITHUB_OUTPUT
          else
            echo "repos=[]" >> $GITHUB_OUTPUT
          fi

  trigger-downstream:
    needs: determine-downstream
    if: needs.determine-downstream.outputs.repos != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ fromJson(needs.determine-downstream.outputs.repos) }}
      max-parallel: 2
      fail-fast: false
    steps:
      - name: Trigger ${{ matrix.repo }} build
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: yourorg/${{ matrix.repo }}
          event-type: upstream-updated
          client-payload: |
            {
              "package": "${{ inputs.package || github.event.client_payload.package }}",
              "version": "${{ inputs.version || github.event.client_payload.version }}",
              "release_type": "${{ inputs.release_type || github.event.client_payload.release_type }}",
              "triggeredBy": "${{ github.actor }}"
            }

      - name: Wait for build
        uses: fountainhead/action-wait-for-check@v1.1.0
        with:
          token: ${{ secrets.PAT_TOKEN }}
          checkName: test-and-build
          ref: main
          repo: ${{ matrix.repo }}
          owner: yourorg
          timeoutSeconds: 600

  create-release-summary:
    needs: [determine-downstream, trigger-downstream]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Create summary
        run: |
          echo "# Release Orchestration Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Package:** ${{ inputs.package || github.event.client_payload.package }}" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** ${{ inputs.version || github.event.client_payload.version }}" >> $GITHUB_STEP_SUMMARY
          echo "**Release Type:** ${{ inputs.release_type || github.event.client_payload.release_type }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Downstream Repos Triggered:**" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "${{ needs.determine-downstream.outputs.repos }}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Notify on Slack (optional)
        if: inputs.release_type != 'dev'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Release orchestration completed",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "🚀 *Release Orchestration Completed*\n\n*Package:* ${{ inputs.package }}\n*Version:* ${{ inputs.version }}\n*Status:* ${{ job.status }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

