# Example: Core Library Publish Workflow
# Use this in: c3-shared, c3-parsing, c3-compliance, c3-projection, c3-discovery, c3-wiring
# Location: .github/workflows/publish.yml

name: Publish Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (dev, canary, patch, minor, major)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - canary
          - patch
          - minor
          - major

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@yourorg'

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

  publish-dev:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@yourorg'

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Version (dev)
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          npm version prerelease --preid=dev.${SHORT_SHA} --no-git-tag-version

      - name: Build
        run: npm run build

      - name: Publish to GitHub Packages
        run: npm publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger downstream builds
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: yourorg/c3-platform
          event-type: dependency-updated
          client-payload: |
            {
              "package": "${{ github.repository }}",
              "version": "${{ steps.version.outputs.version }}",
              "sha": "${{ github.sha }}"
            }

  publish-release:
    needs: test
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@yourorg'

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Version bump
        id: version
        run: |
          if [ "${{ inputs.release_type }}" = "canary" ]; then
            npm version prerelease --preid=canary
          else
            npm version ${{ inputs.release_type }}
          fi
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Build
        run: npm run build

      - name: Create git tag
        run: |
          git tag v${{ steps.version.outputs.version }}
          git push origin v${{ steps.version.outputs.version }}

      - name: Publish to GitHub Packages
        run: |
          if [ "${{ inputs.release_type }}" = "canary" ]; then
            npm publish --tag canary
          else
            npm publish --tag latest
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        if: inputs.release_type != 'canary' && inputs.release_type != 'dev'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false

      - name: Trigger downstream builds
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: yourorg/c3-platform
          event-type: dependency-updated
          client-payload: |
            {
              "package": "${{ github.repository }}",
              "version": "${{ steps.version.outputs.version }}",
              "release_type": "${{ inputs.release_type }}"
            }

