# Example: Simplified Application CI using Registry
# Use this in: c3-bff, c3-cli, c3-web
# Location: .github/workflows/ci.yml

name: Application CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  repository_dispatch:
    types: [upstream-updated]
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@yourorg'
          cache: 'npm'

      - name: Configure npm for GitHub Packages
        run: |
          echo "@yourorg:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run linter
        run: npm run lint
        continue-on-error: true

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.node-version }}
          path: dist/
          retention-days: 7

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.node-version }}
          path: coverage/
          retention-days: 7

  # Optional: Deploy stage
  deploy-staging:
    needs: test-and-build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-20.x
          path: dist/

      - name: Deploy to staging
        run: |
          echo "Deploying to staging..."
          # Add your deployment logic here
          # e.g., deploy to Vercel, AWS, etc.

  # Optional: Notify on upstream changes
  check-upstream-changes:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Log upstream update
        run: |
          echo "Upstream dependency updated:"
          echo "Package: ${{ github.event.client_payload.package }}"
          echo "Version: ${{ github.event.client_payload.version }}"

      - name: Comment on PRs
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pulls } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            
            for (const pull of pulls) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pull.number,
                body: `🔄 Upstream dependency updated: \`${{ github.event.client_payload.package }}\` → \`${{ github.event.client_payload.version }}\`\n\nThis build will use the latest version.`
              });
            }

